#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 12 07:47:38 2025

Load results generated by ProposedAccuracy.py and generate plots.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl


if __name__ == "__main__":
    plt.style.use("seaborn-v0_8-whitegrid")
    fsize = (9.6, 5.76)
    mpl.rcParams['figure.dpi'] = 600

    folder = "MNIST_ln"
    loadname = "MNIST_partial_ln_subset_labelAdaDetect_LR_SVC"

    in_data = np.load(f"{folder}/{loadname}.npz")
    save_res = True
    scalar_metrics = False
    zval = 1

    name_list = ["Storey", "Quantile", "Sum", "Fisher"]
    color_list = ["color1", "color2", "color4", "color3"]
    colors_ = ["tab:orange", "tab:olive", "tab:purple", "tab:red"]

    with open(f"{folder}/{loadname}.txt", "r") as file:
        lines = file.readlines()
        Kminus1 = eval(lines[2].split(" ")[1][:-1])
        K = Kminus1 + 1
        n = eval(lines[4].split(" ")[1][:-1])
        m = eval(lines[5].split(" ")[1][:-1])
        assert lines[4].split(" ")[0][0] == "n", ""
        pi_model = lines[10].split(" ")[-1][:-1]
        if lines[10].split(" ")[0] != "pi":
            pi_model = lines[12].split(" ")[-1][:-1]
            assert lines[12].split(" ")[0] == "pi"
        else:
            assert lines[10].split(" ")[0] == "pi"
        include = list()
        for inc in lines[-1].split(", ")[:-1]:
            include.append(inc)

    print(include)

    if "baseline" in include:
        model_scores_baselines_mean = np.mean(in_data["model_scores_baselines"], axis=0)
        bought_data_baselines_mean = np.mean(in_data["bought_data_baselines"]/m, axis=0)
        used_data_baselines_mean = np.mean(in_data["used_data_baselines"], axis=0)
        print(f'{np.mean(in_data["model_scores_baselines"]*100, axis=0)[0]:.3f} ({np.std(in_data["model_scores_baselines"]*100, axis=0)[0]:.3f})')

    if "baseline_COD" in include:
        model_scores_baselines_COD_mean = np.mean(in_data["model_scores_baselines_COD"], axis=0)
        bought_data_baselines_COD_mean = np.mean(in_data["bought_data_baselines_COD"]/m, axis=0)
        used_data_baselines_COD_mean = np.mean(in_data["used_data_baselines_COD"], axis=0)

    if "oracle" in include:
        model_scores_oracles_mean = np.mean(in_data["model_scores_oracles"], axis=0)
        bought_data_oracles_mean = np.mean(in_data["bought_data_oracles"]/m, axis=0)
        used_data_oracles_mean = np.mean(in_data["used_data_oracles"], axis=0)

    if "oracleth" in include:
        model_scores_oraclesth_mean = np.mean(in_data["model_scores_oraclesth"], axis=0)
        bought_data_oraclesth_mean = np.mean(in_data["bought_data_oraclesth"]/m, axis=0)
        used_data_oraclesth_mean = np.mean(in_data["used_data_oraclesth"], axis=0)

    if "oracle_COD" in include:
        model_scores_partoracles_mean = np.mean(in_data["model_scores_partoracles"], axis=0)
        bought_data_partoracles_mean = np.mean(in_data["bought_data_partoracles"]/m, axis=0)
        used_data_partoracles_mean = np.mean(in_data["used_data_partoracles"], axis=0)

    if "oracle_CODth" in include:
        model_scores_partoracles_th_mean = np.mean(in_data["model_scores_partoracles_th"], axis=0)
        bought_data_partoracles_th_mean = np.mean(in_data["bought_data_partoracles_th"]/m, axis=0)
        used_data_partoracles_th_mean = np.mean(in_data["used_data_partoracles_th"], axis=0)

    if "oracle_CODth_picky" in include:
        model_scores_partoracles_th_picky_mean = np.mean(in_data["model_scores_partoracles_th_picky"], axis=0)
        bought_data_partoracles_th_picky_mean = np.mean(in_data["bought_data_partoracles_th_picky"]/m, axis=0)
        used_data_partoracles_th_picky_mean = np.nanmean(in_data["used_data_partoracles_th_picky"], axis=0)

    if "proposed" in include:
        model_scores_proposed_mean = np.mean(in_data["model_scores_proposed"], axis=0)
        bought_data_proposed_mean = np.mean(in_data["bought_data_proposed"]/m, axis=0)
        used_data_proposed_mean = np.mean(in_data["used_data_proposed"], axis=0)

    if "proposed_picky" in include:
        model_scores_proposed_picky_mean = np.mean(in_data["model_scores_proposed_picky"], axis=0)
        bought_data_proposed_picky_mean = np.mean(in_data["bought_data_proposed_picky"]/m, axis=0)
        used_data_proposed_picky_mean = np.mean(in_data["used_data_proposed_picky"], axis=0)

    sims = in_data["model_scores_proposed"].shape[0]

    # =============================================================================
    # Accuracy plot
    # =============================================================================
    alpha_idx = np.ones(bought_data_proposed_mean.shape[1], dtype=bool)
    colors = ["tab:blue", "tab:orange", "tab:green", "tab:red", "tab:purple", "tab:brown", "tab:pink", "tab:gray", "tab:olive", "tab:cyan", "k"]
    _ = plt.figure(figsize=fsize)
    if "baseline" in include:
        plt.plot(bought_data_baselines_mean, model_scores_baselines_mean, "o", color=colors[0], label="Fixed budget")
    if "baseline_COD" in include:
        plt.plot(bought_data_baselines_COD_mean, model_scores_baselines_COD_mean, "*", color=colors[0], label="Fixed budget (COD)")
    if "oracle" in include:
        plt.plot(bought_data_oracles_mean, model_scores_oracles_mean, "o", color=colors[2], label="Oracle")
    if "oracleth" in include:
        plt.plot(bought_data_oraclesth_mean, model_scores_oraclesth_mean, "1", color=colors[2], label="Oracle threshold")
    if "oracle_COD" in include:
        plt.plot(bought_data_partoracles_mean, model_scores_partoracles_mean, "*", color=colors[9], label="Oracle all data")
    if "oracle_CODth" in include:
        plt.plot(bought_data_partoracles_th_mean, model_scores_partoracles_th_mean, "1", color=colors[9], label="Oracle threshold all data")
    if "oracle_CODth_picky" in include:
        plt.plot(bought_data_partoracles_th_picky_mean, model_scores_partoracles_th_picky_mean, "x", color=colors[9], label="Oracle picky")
    if "proposed" in include:
        plt.plot(bought_data_proposed_mean[:, alpha_idx, 0].flatten(), model_scores_proposed_mean[:, alpha_idx, 0].flatten(), "o", color=colors_[0], label="Storey")
        plt.plot(bought_data_proposed_mean[:, alpha_idx, 1].flatten(), model_scores_proposed_mean[:, alpha_idx, 1].flatten(), "o", color=colors_[1], label="Quantile")
        plt.plot(bought_data_proposed_mean[:, alpha_idx, 2].flatten(), model_scores_proposed_mean[:, alpha_idx, 2].flatten(), "o", color=colors_[2], label="Summation")
        plt.plot(bought_data_proposed_mean[:, alpha_idx, 3].flatten(), model_scores_proposed_mean[:, alpha_idx, 3].flatten(), "o", color=colors_[3], label="Fisher")
    if "proposed_picky" in include:
        plt.plot(bought_data_proposed_picky_mean[:, alpha_idx, 0].flatten(), model_scores_proposed_picky_mean[:, alpha_idx, 0].flatten(), "x", color=colors_[0], label="Storey picky")
        plt.plot(bought_data_proposed_picky_mean[:, alpha_idx, 1].flatten(), model_scores_proposed_picky_mean[:, alpha_idx, 1].flatten(), "x", color=colors_[1], label="Quantile picky")
        plt.plot(bought_data_proposed_picky_mean[:, alpha_idx, 2].flatten(), model_scores_proposed_picky_mean[:, alpha_idx, 2].flatten(), "x", color=colors_[2], label="Summation picky")
        plt.plot(bought_data_proposed_picky_mean[:, alpha_idx, 3].flatten(), model_scores_proposed_picky_mean[:, alpha_idx, 3].flatten(), "x", color=colors_[3], label="Fisher picky")
    plt.xlabel("Budget")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.show()
